import Navigation from "./components/navigation"
import SalesLayout$ from "./about-us/company/jobs/sales/layout";
import Sales from "./about-us/company/jobs/sales/page";
import { Metadata } from "next";
import "../app/styles/global.css";

export const metadata :Metadata = {
  title: {
    template: "%s | next movies",
    default: "baby"
  },
  description: "Generated by Next.js",
}

export default function Layout({
  children,
}: { 
  children: React.ReactNode
  }) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
